[server]
address = "0.0.0.0:8080"
read_only = false
danger_dummy_mode = false
max_file_count = 1
temporary_directory = "/tmp"
cleanup_temporary_directory = true

[client]
timeout = 30

[upgrade]
concurrency = 32

[tracing.logging]
format = "normal"
targets = "info"
log_spans = false
no_ansi = false

[tracing.console]
buffer_capacity = 102400

[tracing.opentelemetry]
service_name = "pict-rs"
targets = "info"

[metrics]

[old_repo]

[media]
external_validation_timeout = 30
max_file_size = 40
process_timeout = 30
filters = [
    "blur",
    "crop",
    "identity",
    "resize",
    "thumbnail",
]

[media.retention]
variants = "7d"
proxy = "7d"

[media.magick]
max_width = 10000
max_height = 10000
max_area = 20000
memory = 256
map = 512
disk = 1024

[media.image]
max_width = 10000
max_height = 10000
max_area = 40000000
max_file_size = 40

[media.animation]
max_width = 1920
max_height = 1920
max_area = 2073600
max_file_size = 40
max_frame_count = 900

[media.video]
enable = true
allow_audio = false
max_width = 3840
max_height = 3840
max_area = 8294400
max_file_size = 40
max_frame_count = 900

[media.video.quality]
crf_max = 32

[repo]
type = "sled"
path = "/mnt/sled-repo"
cache_capacity = 67108864
export_path = "/mnt/exports"

[store]
type = "filesystem"
path = "/mnt/files"
