[server]
address = "0.0.0.0:8080"
worker_id = "pict-rs-1"
client_pool_size = 100

[tracing.logging]
format = "normal"
targets = "warn,tracing_actix_web=info,actix_server=info,actix_web=info"

[tracing.console]
buffer_capacity = 102400

[tracing.opentelemetry]
service_name = "pict-rs"
targets = "info"

[old_db]
path = "/mnt"

[media]
max_width = 10000
max_height = 10000
max_area = 40000000
max_file_size = 40
max_frame_count = 900
enable_silent_video = true
enable_full_video = false
video_codec = "vp9"
filters = [
    "blur",
    "crop",
    "identity",
    "resize",
    "thumbnail",
]
skip_validate_imports = false

[media.gif]
max_width = 128
max_height = 128
max_area = 16384
max_frame_count = 100

[repo]
type = "sled"
path = "/mnt/sled-repo"
cache_capacity = 67108864
export_path = "/mnt/exports"

[store]
type = "filesystem"
path = "/mnt/files"
