[server]
address = "0.0.0.0:8080"
read_only = false
max_file_count = 1

[client]
pool_size = 100
timeout = 30

[tracing.logging]
format = "normal"
targets = "info"

[tracing.console]
buffer_capacity = 102400

[tracing.opentelemetry]
service_name = "pict-rs"
targets = "info"

[metrics]

[old_repo]
path = "/mnt/sled-repo"
cache_capacity = 67108864
export_path = "/mnt/exports"

[media]
external_validation_timeout = 30
max_file_size = 40
process_timeout = 30
filters = [
    "blur",
    "crop",
    "identity",
    "resize",
    "thumbnail",
]

[media.retention]
variants = "7d"
proxy = "7d"

[media.image]
max_width = 10000
max_height = 10000
max_area = 40000000
max_file_size = 40

[media.animation]
max_width = 1920
max_height = 1920
max_area = 2073600
max_file_size = 40
max_frame_count = 900

[media.video]
enable = true
allow_audio = false
max_width = 3840
max_height = 3840
max_area = 8294400
max_file_size = 40
max_frame_count = 900

[media.video.quality]
crf_max = 32

[repo]
type = "sled"
path = "/mnt/sled-repo"
cache_capacity = 67108864
export_path = "/mnt/exports"

[store]
type = "filesystem"
path = "/mnt/files"
