on: 
  push:
  pull_request:
    branches:
      - main

jobs:
  clippy:
    runs-on: docker
    container:
      image: docker.io/node:20-bookworm
    steps:
      -
        name: Checkout pict-rs
        uses: https://github.com/actions/checkout@v4
      -
        name: Install rustup and rust
        uses: https://github.com/dtolnay/rust-toolchain@1.75.0
        with:
          components: clippy
      -
        name: Clippy
        run: |
          cargo clippy --no-default-features -- -D warnings
          cargo clippy --no-default-features --features io-uring -- -D warnings

  tests:
    runs-on: docker
    container:
      image: docker.io/node:20-bookworm
    steps:
      -
        name: Checkout pict-rs
        uses: https://github.com/actions/checkout@v4
      -
        name: Install rustup and rust
        uses: https://github.com/dtolnay/rust-toolchain@1.75.0
      -
        name: Test
        run: cargo test

  check:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
          - aarch64-unknown-linux-musl
    runs-on: docker
    container:
      image: docker.io/node:20-bookworm
    steps:
      -
        name: Checkout pict-rs
        uses: https://github.com/actions/checkout@v4
      -
        name: Install rustup and rust
        uses: https://github.com/dtolnay/rust-toolchain@1.75.0
        with:
          targets: ${{ matrix.target }}
      -
        name: Install cargo-binstall
        uses: https://github.com/taiki-e/install-action@v2
        with:
          tool: cargo-binstall
      -
        name: Install zig
        uses: https://github.com/goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      -
        name: Install cargo-zigbuild
        run: yes | cargo binstall cargo-zigbuild
      -
        name: Debug builds
        run: cargo zigbuild --debug --target ${{ matrix.target }}
