on: 
  push:
  pull_request:
    branches:
      - main

jobs:
  checkout:
    runs-on: docker
    container:
      image: docker.io/node:20-alpine3.19
    steps:
      - uses: actions/checkout@v4

  clippy:
    needs: [checkout]
    runs-on: docker
    container:
      image: docker.io/asonix/rust-builder:latest-linux-amd64
    steps:
      - run: rustup component add clippy
      - run: cargo clippy --no-default-features -- -D warnings
      - run: cargo clippy --no-default-features --features io-uring -- -D warnings

  tests:
    needs: [checkout]
    runs-on: docker
    container:
      image: docker.io/asonix/rust-builder:latest-linux-amd64
    steps:
      - uses: actions/checkout@v4
      - run: cargo test
