on: 
  push:
  pull_request:
    branches:
      - main

jobs:
  clippy:
    runs-on: docker
    container:
      image: docker.io/asonix/rust-builder:latest-linux-amd64
    steps:
      - uses: actions/checkout@v4
      - rustup component add clippy
      - cargo clippy --no-default-features -- -D warnings
      - cargo clippy --no-default-features --features io-uring -- -D warnings

  tests:
    runs-on: docker
    container:
      image: docker.io/asonix/rust-builder:latest-linux-amd64
    steps:
      - uses: actions/checkout@v4
      - cargo test
