on: 
  push:
  pull_request:
    branches:
      - main

jobs:
  clippy:
    runs-on: docker
    container:
      image: docker.io/node:20-bookworm
    steps:
      -
        name: Checkout pict-rs
        uses: https://github.com/actions/checkout@v4
      -
        name: Setup Rust
        uses: https://git.asonix.dog/asonix/pict-rs/.forgejo/actions/prepare-rust@main
      -
        name: Clippy
        run: |
          cargo clippy --no-default-features -- -D warnings
          cargo clippy --no-default-features --features io-uring -- -D warnings

  tests:
    runs-on: docker
    container:
      image: docker.io/node:20-bookworm
    steps:
      -
        name: Checkout pict-rs
        uses: https://github.com/actions/checkout@v4
      -
        name: Setup Rust
        uses: https://git.asonix.dog/asonix/pict-rs/.forgejo/actions/prepare-rust@main
      -
        name: Test
        run: cargo test

  check:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
          - aarch64-unknown-linux-musl
    runs-on: docker
    container:
      image: docker.io/node:20-bookworm
    steps:
      -
        name: Checkout pict-rs
        uses: https://github.com/actions/checkout@v4
      -
        name: Setup Rust
        uses: https://git.asonix.dog/asonix/pict-rs/.forgejo/actions/prepare-rust@main
        with:
          targets: |
             ["x86_64-unknown-linux-musl",
              "armv7-unknown-linux-musleabihf",
              "aarch64-unknown-linux-musl"]
      -
        name: Debug builds
        run: cargo zigbuild --target ${{ matrix.target }}
