on: 
  push:
  pull_request:
    branches:
      - main

jobs:
  test-action:
    runs-on: docker
    container:
      image: docker.io/node:20-bookworm
    steps:
      - uses: actions/checkout@v4
      - uses: ./.forgejo/actions/build-amd64
        with:
          name: pict-rs
          action: clippy
          build_mode: debug

  clippy:
    runs-on: docker
    container:
      image: docker.io/asonix/rust-builder:latest-linux-amd64
    steps:
      - run: |
          git clone ${{ env.github_server_url }}/${{ env.github_repository }} .
          git checkout ${{ env.github_sha }}
          rustup component add clippy
          cargo clippy --no-default-features -- -D warnings
          cargo clippy --no-default-features --features io-uring -- -D warnings

  tests:
    runs-on: docker
    container:
      image: docker.io/asonix/rust-builder:latest-linux-amd64
    steps:
      - run: |
          git clone ${{ env.github_server_url }}/${{ env.github_repository }} .
          git checkout ${{ env.github_sha }}
          cargo test

  check:
    strategy:
      matrix:
        include:
          - image: docker.io/asonix/rust-builder:latest-linux-amd64
            target: x86_64-unknown-linux-musl
          - image: docker.io/asonix/rust-builder:latest-linux-arm32v7
            target: armv7-unknown-linux-musleabihf
          - image: docker.io/asonix/rust-builder:latest-linux-arm64v8
            target: aarch64-unknown-linux-musl
    runs-on: docker
    container:
      image: ${{ matrix.image }}
    steps:
      - run: |
          git clone ${{ env.github_server_url }}/${{ env.github_repository }} .
          git checkout ${{ env.github_sha }}
          cargo check --target ${{ matrix.target }}
