version: '3.3'

services:
  #  pictrs:
  #    build:
  #      context: .
  #      dockerfile: ./Dockerfile
  #      args:
  #        UID: "${USER_ID:-1000}"
  #        GID: "${GROUP_ID:-1000}"
  #    ports:
  #      - "8080:8080"
  #      - "6669:6669"
  #    environment:
  #      - PICTRS__TRACING__CONSOLE__ADDRESS=0.0.0.0:6669
  #      - PICTRS__TRACING__OPENTELEMETRY__URL=http://otel:4137
  #      - RUST_BACKTRACE=1
  #    stdin_open: true
  #    tty: true
  #    volumes:
  #      - ./storage/pict-rs:/mnt
  #      - ../../:/opt/app

  # pictrs_proxy:
  #   image: asonix/pictrs-proxy:0.4.0-rc.2
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - PICTRS_PROXY_UPSTREAM=http://pictrs:8080
  #     - PICTRS_PROXY_OPENTELEMETRY_URL=http://otel:4137

  minio:
    image: quay.io/minio/minio
    command: server /mnt --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage/minio:/mnt

  garage:
    image: dxflrs/garage:v0.8.1
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
      - "3903:3903"
      - "3904:3904"
    environment:
      - RUST_LOG=debug
    volumes:
      - ./storage/garage:/mnt
      - ./garage.toml:/etc/garage.toml

  otel:
    image: otel/opentelemetry-collector:latest
    command: --config otel-local-config.yaml
    volumes:
      - type: bind
        source: ./otel.yml
        target: /otel-local-config.yaml
    restart: always
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1
    ports:
      - "14250:14250"
      # To view traces, visit http://localhost:16686
      - "16686:16686"
    restart: always
